### ISSUE TITLE
Doesn't support older PCL projects profiles

### ISSUE THREAD

**Issue by alvynfash** [ChasakisD/XFShimmerLayout#1]
Fails to install on PCL projects with Profile49 etc with message:

"Could not install package 'XFShimmerLayout 1.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile49', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

*Seems to be targeting netStandard 2.0*

**Comment by ChasakisD** [comment]
This project targets .Net Standard 2.0. in order to add it to your project, you must not have a PCL but a .Net Standard project.

**Comment by alvynfash** [comment]
Can you add backward compatibility as many older projects haven’t migrated just yet. The drawing engine that this olugin uses itself supports older PCLs so it shouldn’t be a problem either.
Thanks

**Comment by ChasakisD** [comment]
Currently VS 2019 both for Windows and Mac, are not able to create PCL Project. Feel free to create a PCL Project if you are able to and PR it. After that, i will make it backwards compatible :)

**Comment by alvynfash** [comment]
Hi, I made a PR some days ago with your demands, any updates?

**Comment by ChasakisD** [comment]
Sorry for my late response, at this moment, this is my exams period so my time is limited. I will check it as soon as possible :)

**Comment by alvynfash** [comment]
@ChasakisD Hope exams are great, any updates so far ?

**Comment by ChasakisD** [comment]
Hi @alvynfash, i was thinking out a way to not duplicate all the code, but creating a project that will be out code base, and then we will have 2 sub projects, one .net standard and one pcl to reference that assembly. Although i do not think if it is worth supporting pcl's anymore, cuz it is very simple to migrate to .net standard.

**Comment by alvynfash** [comment]
@ChasakisD while migration indeed is straight-forward, Enterprise-level projects are a bit trickier to migrate as there's a whole stack of dependencies. I believe you can simply use the "Bait and switch with .NET Standard" like most do to allow backward compability as described in this link : [https://forums.dotnetfoundation.org/t/bait-and-switch-with-net-standard/2668](url)

**Comment by alvynfash** [comment]
@ChasakisD any updates? I guess you had a good run till now that they've gone ahead and implemented this => [https://www.syncfusion.com/blogs/post/introducing-xamarin-forms-shimmer.aspx](url)
