### ISSUE TITLE
OnParentSet throws NullReferenceException when _maskCanvasView is null

### ISSUE THREAD

**Issue by saverioroncolini** [ChasakisD/XFShimmerLayout#3]
OnParentSet throws NullReferenceException when _maskCanvasView is null.

I fixed it substituting 

            if (Parent != null) return;

with

            if (Parent != null || _maskCanvasView is null) return;

Maybe it could be pushed in master.

Thanks for your great work

**Comment by ChasakisD** [comment]
Alright! Thanks for the feedback! Feel free to make a pull request

**Comment by ChasakisD** [comment]
Version 1.0.1 will be uploaded asap
